Task 2.3 Training management system
stoyankisyov/dotNetSchool pull request #6
Opened 2024-04-26 17:00 UTC by stoyankisyov

2024-05-02 11:38 UTC, IgorKheidorov requested changes
Good but fix comments about clone and tests

2024-05-02 11:38 UTC, IgorKheidorov commented on TrainingManagementSystem/Training.cs
> +{
Better Training: TrainigEntity (which includes decription)
      Lesson: TrainingUnit: TrainingEntity

Add one more abstract class,

2024-05-02 11:38 UTC, IgorKheidorov commented on TrainingManagementSystem/Training.cs
> +            {
to avoid this casting each time use interface-> standard IClonable, or create your own

2024-05-02 11:38 UTC, IgorKheidorov commented on TrainingManagementSystemTests/LectureTests.cs
> +            var clonedLecture = lecture.Clone();
Here you check only that the references are different, but you the success of clone that objects are different, but content is the same by meaning, not by references.

2024-05-02 15:43 UTC, stoyankisyov commented on TrainingManagementSystem/Training.cs
> +{
Fixed.

2024-05-02 15:43 UTC, stoyankisyov commented on TrainingManagementSystem/Training.cs
> +            {
Fixed.

2024-05-02 15:43 UTC, stoyankisyov commented on TrainingManagementSystemTests/LectureTests.cs
> +            var clonedLecture = lecture.Clone();
Fixed.

2024-05-07 11:26 UTC, IgorKheidorov approved these changes

2024-05-08 12:26 UTC, merged